# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cerbos.cloud.bundle.v1 import bundle_pb2 as cerbos_dot_cloud_dot_bundle_dot_v1_dot_bundle__pb2


class CerbosBundleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBundle = channel.unary_unary(
                '/cerbos.cloud.bundle.v1.CerbosBundleService/GetBundle',
                request_serializer=cerbos_dot_cloud_dot_bundle_dot_v1_dot_bundle__pb2.GetBundleRequest.SerializeToString,
                response_deserializer=cerbos_dot_cloud_dot_bundle_dot_v1_dot_bundle__pb2.GetBundleResponse.FromString,
                _registered_method=True)
        self.WatchBundle = channel.stream_stream(
                '/cerbos.cloud.bundle.v1.CerbosBundleService/WatchBundle',
                request_serializer=cerbos_dot_cloud_dot_bundle_dot_v1_dot_bundle__pb2.WatchBundleRequest.SerializeToString,
                response_deserializer=cerbos_dot_cloud_dot_bundle_dot_v1_dot_bundle__pb2.WatchBundleResponse.FromString,
                _registered_method=True)


class CerbosBundleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBundle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchBundle(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CerbosBundleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBundle': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBundle,
                    request_deserializer=cerbos_dot_cloud_dot_bundle_dot_v1_dot_bundle__pb2.GetBundleRequest.FromString,
                    response_serializer=cerbos_dot_cloud_dot_bundle_dot_v1_dot_bundle__pb2.GetBundleResponse.SerializeToString,
            ),
            'WatchBundle': grpc.stream_stream_rpc_method_handler(
                    servicer.WatchBundle,
                    request_deserializer=cerbos_dot_cloud_dot_bundle_dot_v1_dot_bundle__pb2.WatchBundleRequest.FromString,
                    response_serializer=cerbos_dot_cloud_dot_bundle_dot_v1_dot_bundle__pb2.WatchBundleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cerbos.cloud.bundle.v1.CerbosBundleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cerbos.cloud.bundle.v1.CerbosBundleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CerbosBundleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBundle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cerbos.cloud.bundle.v1.CerbosBundleService/GetBundle',
            cerbos_dot_cloud_dot_bundle_dot_v1_dot_bundle__pb2.GetBundleRequest.SerializeToString,
            cerbos_dot_cloud_dot_bundle_dot_v1_dot_bundle__pb2.GetBundleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchBundle(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cerbos.cloud.bundle.v1.CerbosBundleService/WatchBundle',
            cerbos_dot_cloud_dot_bundle_dot_v1_dot_bundle__pb2.WatchBundleRequest.SerializeToString,
            cerbos_dot_cloud_dot_bundle_dot_v1_dot_bundle__pb2.WatchBundleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
