# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/cloud/auth/v1/auth.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'cerbos/cloud/auth/v1/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63\x65rbos/cloud/auth/v1/auth.proto\x12\x14\x63\x65rbos.cloud.auth.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"g\n\x11\x43lientCredentials\x12$\n\tclient_id\x18\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x08\x63lientId\x12,\n\rclient_secret\x18\x02 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x0c\x63lientSecret\"\xc9\x01\n\x0b\x44\x65viceToken\x12*\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x0b\x61\x63\x63\x65ssToken\x12,\n\rrefresh_token\x18\x02 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x0crefreshToken\x12\x41\n\nexpires_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\texpiresAt\x12\x1d\n\ntoken_type\x18\x04 \x01(\tR\ttokenType\"\xf7\x01\n\x10SavedCredentials\x12+\n\x0c\x61pi_endpoint\x18\x01 \x01(\tB\x08\xbaH\x05r\x03\x80\x02\x01R\x0b\x61piEndpoint\x12X\n\x12\x63lient_credentials\x18\x02 \x01(\x0b\x32\'.cerbos.cloud.auth.v1.ClientCredentialsH\x00R\x11\x63lientCredentials\x12\x46\n\x0c\x64\x65vice_token\x18\x03 \x01(\x0b\x32!.cerbos.cloud.auth.v1.DeviceTokenH\x00R\x0b\x64\x65viceTokenB\x14\n\x0b\x63redentials\x12\x05\xbaH\x02\x08\x01\x42?Z=github.com/cerbos/cloud-api/genpb/cerbos/cloud/auth/v1;authv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerbos.cloud.auth.v1.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/cerbos/cloud-api/genpb/cerbos/cloud/auth/v1;authv1'
  _globals['_CLIENTCREDENTIALS'].fields_by_name['client_id']._loaded_options = None
  _globals['_CLIENTCREDENTIALS'].fields_by_name['client_id']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_CLIENTCREDENTIALS'].fields_by_name['client_secret']._loaded_options = None
  _globals['_CLIENTCREDENTIALS'].fields_by_name['client_secret']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_DEVICETOKEN'].fields_by_name['access_token']._loaded_options = None
  _globals['_DEVICETOKEN'].fields_by_name['access_token']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_DEVICETOKEN'].fields_by_name['refresh_token']._loaded_options = None
  _globals['_DEVICETOKEN'].fields_by_name['refresh_token']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_DEVICETOKEN'].fields_by_name['expires_at']._loaded_options = None
  _globals['_DEVICETOKEN'].fields_by_name['expires_at']._serialized_options = b'\272H\003\310\001\001'
  _globals['_SAVEDCREDENTIALS'].oneofs_by_name['credentials']._loaded_options = None
  _globals['_SAVEDCREDENTIALS'].oneofs_by_name['credentials']._serialized_options = b'\272H\002\010\001'
  _globals['_SAVEDCREDENTIALS'].fields_by_name['api_endpoint']._loaded_options = None
  _globals['_SAVEDCREDENTIALS'].fields_by_name['api_endpoint']._serialized_options = b'\272H\005r\003\200\002\001'
  _globals['_CLIENTCREDENTIALS']._serialized_start=119
  _globals['_CLIENTCREDENTIALS']._serialized_end=222
  _globals['_DEVICETOKEN']._serialized_start=225
  _globals['_DEVICETOKEN']._serialized_end=426
  _globals['_SAVEDCREDENTIALS']._serialized_start=429
  _globals['_SAVEDCREDENTIALS']._serialized_end=676
# @@protoc_insertion_point(module_scope)
