# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: authzen/authorization/v1/svc.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'authzen/authorization/v1/svc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from authzen.authorization.v1 import evaluation_pb2 as authzen_dot_authorization_dot_v1_dot_evaluation__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"authzen/authorization/v1/svc.proto\x12\x18\x61uthzen.authorization.v1\x1a)authzen/authorization/v1/evaluation.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xae\x07\n\x14\x41uthorizationService\x12\x81\x02\n\x08Metadata\x12).authzen.authorization.v1.MetadataRequest\x1a*.authzen.authorization.v1.MetadataResponse\"\x9d\x01\x92\x41p\x12\"Get Policy Decision Point metadata\x1aJReturns the AuthZEN Policy Decision Point metadata including endpoint URLs\x82\xd3\xe4\x93\x02$\x12\"/.well-known/authzen-configuration\x12\x9b\x02\n\x10\x41\x63\x63\x65ssEvaluation\x12\x31.authzen.authorization.v1.AccessEvaluationRequest\x1a\x32.authzen.authorization.v1.AccessEvaluationResponse\"\x9f\x01\x92\x41|\x12\x17\x45valuate access request\x1a\x61\x45valuate whether a subject can perform an action on a resource according to AuthZEN specification\x82\xd3\xe4\x93\x02\x1a\"\x15/access/v1/evaluation:\x01*\x12\xb8\x02\n\x15\x41\x63\x63\x65ssEvaluationBatch\x12\x36.authzen.authorization.v1.AccessEvaluationBatchRequest\x1a\x37.authzen.authorization.v1.AccessEvaluationBatchResponse\"\xad\x01\x92\x41\x88\x01\x12\x1d\x42\x61tch evaluate access request\x1agBatch evaluate whether a subject can perform an action on a resource according to AuthZEN specification\x82\xd3\xe4\x93\x02\x1b\"\x16/access/v1/evaluations:\x01*\x1a\x39\x92\x41\x36\x12\x34\x41uthZEN Authorization Service for access evaluationsB\xbf\x02\n\'dev.cerbos.authzen.api.v1.authorizationZKgithub.com/cerbos/cerbos/api/genpb/authzen/authorization/v1;authorizationv1\xaa\x02#Cerbos.AuthZen.Api.V1.Authorization\x92\x41\x9f\x01\x12v\n\x19\x41uthZEN Authorization API\x12\x37OpenID AuthZEN Authorization API for access evaluations\"\x1c\n\x06\x43\x65rbos\x12\x12https://cerbos.dev2\x02v1*\x01\x02\x32\x10\x61pplication/json:\x10\x61pplication/jsonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'authzen.authorization.v1.svc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\'dev.cerbos.authzen.api.v1.authorizationZKgithub.com/cerbos/cerbos/api/genpb/authzen/authorization/v1;authorizationv1\252\002#Cerbos.AuthZen.Api.V1.Authorization\222A\237\001\022v\n\031AuthZEN Authorization API\0227OpenID AuthZEN Authorization API for access evaluations\"\034\n\006Cerbos\022\022https://cerbos.dev2\002v1*\001\0022\020application/json:\020application/json'
  _globals['_AUTHORIZATIONSERVICE']._loaded_options = None
  _globals['_AUTHORIZATIONSERVICE']._serialized_options = b'\222A6\0224AuthZEN Authorization Service for access evaluations'
  _globals['_AUTHORIZATIONSERVICE'].methods_by_name['Metadata']._loaded_options = None
  _globals['_AUTHORIZATIONSERVICE'].methods_by_name['Metadata']._serialized_options = b'\222Ap\022\"Get Policy Decision Point metadata\032JReturns the AuthZEN Policy Decision Point metadata including endpoint URLs\202\323\344\223\002$\022\"/.well-known/authzen-configuration'
  _globals['_AUTHORIZATIONSERVICE'].methods_by_name['AccessEvaluation']._loaded_options = None
  _globals['_AUTHORIZATIONSERVICE'].methods_by_name['AccessEvaluation']._serialized_options = b'\222A|\022\027Evaluate access request\032aEvaluate whether a subject can perform an action on a resource according to AuthZEN specification\202\323\344\223\002\032\"\025/access/v1/evaluation:\001*'
  _globals['_AUTHORIZATIONSERVICE'].methods_by_name['AccessEvaluationBatch']._loaded_options = None
  _globals['_AUTHORIZATIONSERVICE'].methods_by_name['AccessEvaluationBatch']._serialized_options = b'\222A\210\001\022\035Batch evaluate access request\032gBatch evaluate whether a subject can perform an action on a resource according to AuthZEN specification\202\323\344\223\002\033\"\026/access/v1/evaluations:\001*'
  _globals['_AUTHORIZATIONSERVICE']._serialized_start=186
  _globals['_AUTHORIZATIONSERVICE']._serialized_end=1128
# @@protoc_insertion_point(module_scope)
