# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from authzen.authorization.v1 import evaluation_pb2 as authzen_dot_authorization_dot_v1_dot_evaluation__pb2


class AuthorizationServiceStub:
    """AuthZEN Authorization Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Metadata = channel.unary_unary(
                '/authzen.authorization.v1.AuthorizationService/Metadata',
                request_serializer=authzen_dot_authorization_dot_v1_dot_evaluation__pb2.MetadataRequest.SerializeToString,
                response_deserializer=authzen_dot_authorization_dot_v1_dot_evaluation__pb2.MetadataResponse.FromString,
                _registered_method=True)
        self.AccessEvaluation = channel.unary_unary(
                '/authzen.authorization.v1.AuthorizationService/AccessEvaluation',
                request_serializer=authzen_dot_authorization_dot_v1_dot_evaluation__pb2.AccessEvaluationRequest.SerializeToString,
                response_deserializer=authzen_dot_authorization_dot_v1_dot_evaluation__pb2.AccessEvaluationResponse.FromString,
                _registered_method=True)
        self.AccessEvaluationBatch = channel.unary_unary(
                '/authzen.authorization.v1.AuthorizationService/AccessEvaluationBatch',
                request_serializer=authzen_dot_authorization_dot_v1_dot_evaluation__pb2.AccessEvaluationBatchRequest.SerializeToString,
                response_deserializer=authzen_dot_authorization_dot_v1_dot_evaluation__pb2.AccessEvaluationBatchResponse.FromString,
                _registered_method=True)


class AuthorizationServiceServicer:
    """AuthZEN Authorization Service
    """

    def Metadata(self, request, context):
        """Metadata returns the Policy Decision Point metadata
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AccessEvaluation(self, request, context):
        """Evaluate performs an access evaluation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AccessEvaluationBatch(self, request, context):
        """Evaluate performs an access evaluation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthorizationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Metadata': grpc.unary_unary_rpc_method_handler(
                    servicer.Metadata,
                    request_deserializer=authzen_dot_authorization_dot_v1_dot_evaluation__pb2.MetadataRequest.FromString,
                    response_serializer=authzen_dot_authorization_dot_v1_dot_evaluation__pb2.MetadataResponse.SerializeToString,
            ),
            'AccessEvaluation': grpc.unary_unary_rpc_method_handler(
                    servicer.AccessEvaluation,
                    request_deserializer=authzen_dot_authorization_dot_v1_dot_evaluation__pb2.AccessEvaluationRequest.FromString,
                    response_serializer=authzen_dot_authorization_dot_v1_dot_evaluation__pb2.AccessEvaluationResponse.SerializeToString,
            ),
            'AccessEvaluationBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.AccessEvaluationBatch,
                    request_deserializer=authzen_dot_authorization_dot_v1_dot_evaluation__pb2.AccessEvaluationBatchRequest.FromString,
                    response_serializer=authzen_dot_authorization_dot_v1_dot_evaluation__pb2.AccessEvaluationBatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'authzen.authorization.v1.AuthorizationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('authzen.authorization.v1.AuthorizationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthorizationService:
    """AuthZEN Authorization Service
    """

    @staticmethod
    def Metadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/authzen.authorization.v1.AuthorizationService/Metadata',
            authzen_dot_authorization_dot_v1_dot_evaluation__pb2.MetadataRequest.SerializeToString,
            authzen_dot_authorization_dot_v1_dot_evaluation__pb2.MetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AccessEvaluation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/authzen.authorization.v1.AuthorizationService/AccessEvaluation',
            authzen_dot_authorization_dot_v1_dot_evaluation__pb2.AccessEvaluationRequest.SerializeToString,
            authzen_dot_authorization_dot_v1_dot_evaluation__pb2.AccessEvaluationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AccessEvaluationBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/authzen.authorization.v1.AuthorizationService/AccessEvaluationBatch',
            authzen_dot_authorization_dot_v1_dot_evaluation__pb2.AccessEvaluationBatchRequest.SerializeToString,
            authzen_dot_authorization_dot_v1_dot_evaluation__pb2.AccessEvaluationBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
