---
name: Pull Request
on:
  pull_request:
    branches:
      - main
      - "v*"
permissions: {}
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: |
            ./__pypackages__
          key: ${{ runner.os }}-python-${{ hashFiles('**/pdm.lock') }}

      - name: Install dependencies
        run: ./pw pdm install -G :all

      - name: Generate
        run: ./pw generate

      - name: Format
        run: ./pw format

      - name: Lint
        run: ./pw lint

      - name: Generate changelog
        run: ./pw changelog

      - name: Check repo status
        uses: cerbos/actions/check-repo-status@77b46c5f4ff1aebe72b5a8017d561a0f5a9b6845 # main

      - name: Test
        env:
          CERBOS_HUB_API_ENDPOINT: "${{ secrets.CERBOS_HUB_API_ENDPOINT }}"
          CERBOS_HUB_CLIENT_ID: "${{ secrets.CERBOS_HUB_CLIENT_ID }}"
          CERBOS_HUB_CLIENT_SECRET: "${{ secrets.CERBOS_HUB_CLIENT_SECRET }}"
          CERBOS_HUB_STORE_ID: "${{ secrets.CERBOS_HUB_STORE_ID }}"
        run: ./pw test
