---
name: Pull Request
on:
  pull_request:
    branches:
      - main
      - "v*"
permissions: {}
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ./__pypackages__
          key: ${{ runner.os }}-python-${{ hashFiles('**/pdm.lock') }}

      - name: Install dependencies
        run: ./pw pdm install -G :all

      - name: Generate
        run: ./pw generate

      - name: Format
        run: ./pw format

      - name: Lint
        run: ./pw lint

      - name: Check repo status
        uses: cerbos/actions/check-repo-status@5d22d281c9b3bf9a0c8f6cf19090d182cd24d2a2 # main

      - name: Test
        env:
          CERBOS_HUB_API_ENDPOINT: "${{ secrets.CERBOS_HUB_API_ENDPOINT }}"
          CERBOS_HUB_CLIENT_ID: "${{ secrets.CERBOS_HUB_CLIENT_ID }}"
          CERBOS_HUB_CLIENT_SECRET: "${{ secrets.CERBOS_HUB_CLIENT_SECRET }}"
          CERBOS_HUB_STORE_ID: "${{ secrets.CERBOS_HUB_STORE_ID }}"
        run: ./pw test
