name: Audit GitHub Actions security

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  zizmor:
    name: Audit GitHub Actions security
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Check out code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: cerbos/actions/lint-actions@db2ff6efa4315796b92eec00847c9257b89fae5c # main
